### ISSUE TITLE
testRead() open failed

### ISSUE THREAD

**Issue by gascani** [vladistan/gnu.io.android#1]
Hi, thanks for your work.
I compiled successfully your code but when I try to connect to ttyACM0 i've got this error:

I/GNU.IO  ( 1428): JNI_OnLoad called.
I/GNU.IO  ( 1428): Testing the version.
I/GNU.IO  ( 1428): entering RXTXCommDriver:getDeviceDirectory 
I/GNU.IO  ( 1428): TestREAD.
I/GNU.IO  ( 1428): /dev/ttyUSB3
I/GNU.IO  ( 1428): entering RXTXPort:testRead 
I/GNU.IO  ( 1428): testRead() open failed
I/GNU.IO  ( 1428): leaving RXTXPort:testRead 
I/GNU.IO  ( 1428): TestREAD.
I/GNU.IO  ( 1428): /dev/ttyUSB4
I/GNU.IO  ( 1428): entering RXTXPort:testRead 
I/GNU.IO  ( 1428): testRead() open failed
I/GNU.IO  ( 1428): leaving RXTXPort:testRead 
I/GNU.IO  ( 1428): TestREAD.
I/GNU.IO  ( 1428): /dev/ttyACM0
I/GNU.IO  ( 1428): entering RXTXPort:testRead 
I/GNU.IO  ( 1428): testRead() open failed
I/GNU.IO  ( 1428): leaving RXTXPort:testRead 
I/GNU.IO  ( 1428): entering RXTXCommDriver:getDeviceDirectory 
I/GNU.IO  ( 1428): TestREAD.
I/GNU.IO  ( 1428): /dev/ttyUSB3
I/GNU.IO  ( 1428): entering RXTXPort:testRead 
I/GNU.IO  ( 1428): testRead() open failed
I/GNU.IO  ( 1428): leaving RXTXPort:testRead 
I/GNU.IO  ( 1428): TestREAD.
I/GNU.IO  ( 1428): /dev/ttyUSB4
I/GNU.IO  ( 1428): entering RXTXPort:testRead 
I/GNU.IO  ( 1428): testRead() open failed
I/GNU.IO  ( 1428): leaving RXTXPort:testRead 
I/GNU.IO  ( 1428): TestREAD.
I/GNU.IO  ( 1428): /dev/ttyACM0
I/GNU.IO  ( 1428): entering RXTXPort:testRead 
I/GNU.IO  ( 1428): testRead() open failed
I/GNU.IO  ( 1428): leaving RXTXPort:testRead 

How can I fix this? 

Cheers
Giorgio

**Comment by aferre** [comment]
Same thing here, can't use ttyS0 to S4

**Comment by gascani** [comment]
you have to give permission to ttyS0

chmod 777 /dev/ttyS0

If doesn't work restart and try again :)

**Comment by aferre** [comment]
I rooted my IGEP board (I use this instead of a phone) with Z4root, and tried to connect to ttyS0 through ttyS3, after typing chmod 777 on those devices but it still doesn't work.

01-01 00:05:13.195: INFO/GNU.IO(1335): entering RXTXCommDriver:getDeviceDirectory 
01-01 00:05:13.203: INFO/GNU.IO(1335): TestREAD.
01-01 00:05:13.203: INFO/GNU.IO(1335): /dev/ttyS0
01-01 00:05:13.203: INFO/GNU.IO(1335): entering RXTXPort:testRead 
01-01 00:05:13.203: INFO/GNU.IO(1335): RXTX fhs_lock() Error: creating lock file: /data/local/tmp/LCK..ttyS0: Permission denied
01-01 00:05:13.203: INFO/GNU.IO(1335): leaving RXTXPort:testRead no lock 
01-01 00:05:13.203: INFO/GNU.IO(1335): TestREAD.
01-01 00:05:13.203: INFO/GNU.IO(1335): /dev/ttyS1
01-01 00:05:13.203: INFO/GNU.IO(1335): entering RXTXPort:testRead 
01-01 00:05:13.203: INFO/GNU.IO(1335): RXTX fhs_lock() Error: creating lock file: /data/local/tmp/LCK..ttyS1: Permission denied
01-01 00:05:13.203: INFO/GNU.IO(1335): leaving RXTXPort:testRead no lock 
01-01 00:05:13.210: INFO/GNU.IO(1335): TestREAD.
01-01 00:05:13.210: INFO/GNU.IO(1335): /dev/ttyS2
01-01 00:05:13.210: INFO/GNU.IO(1335): entering RXTXPort:testRead 
01-01 00:05:13.210: INFO/GNU.IO(1335): RXTX fhs_lock() Error: creating lock file: /data/local/tmp/LCK..ttyS2: Permission denied
01-01 00:05:13.210: INFO/GNU.IO(1335): leaving RXTXPort:testRead no lock 
01-01 00:05:13.210: INFO/GNU.IO(1335): TestREAD.
01-01 00:05:13.210: INFO/GNU.IO(1335): /dev/ttyS3
01-01 00:05:13.210: INFO/GNU.IO(1335): entering RXTXPort:testRead 
01-01 00:05:13.210: INFO/GNU.IO(1335): RXTX fhs_lock() Error: creating lock file: /data/local/tmp/LCK..ttyS3: Permission denied
01-01 00:05:13.210: INFO/GNU.IO(1335): leaving RXTXPort:testRead no lock 
01-01 00:05:13.281: INFO/GNU.IO(1335): entering RXTXCommDriver:getDeviceDirectory 
01-01 00:05:13.289: INFO/GNU.IO(1335): TestREAD.
01-01 00:05:13.289: INFO/GNU.IO(1335): /dev/ttyS0
01-01 00:05:13.289: INFO/GNU.IO(1335): entering RXTXPort:testRead 
01-01 00:05:13.289: INFO/GNU.IO(1335): RXTX fhs_lock() Error: creating lock file: /data/local/tmp/LCK..ttyS0: Permission denied
01-01 00:05:13.289: INFO/GNU.IO(1335): leaving RXTXPort:testRead no lock 
01-01 00:05:13.289: INFO/GNU.IO(1335): TestREAD.
01-01 00:05:13.289: INFO/GNU.IO(1335): /dev/ttyS1
01-01 00:05:13.289: INFO/GNU.IO(1335): entering RXTXPort:testRead 
01-01 00:05:13.289: INFO/GNU.IO(1335): RXTX fhs_lock() Error: creating lock file: /data/local/tmp/LCK..ttyS1: Permission denied
01-01 00:05:13.289: INFO/GNU.IO(1335): leaving RXTXPort:testRead no lock 
01-01 00:05:13.289: INFO/GNU.IO(1335): TestREAD.
01-01 00:05:13.289: INFO/GNU.IO(1335): /dev/ttyS2
01-01 00:05:13.289: INFO/GNU.IO(1335): entering RXTXPort:testRead 
01-01 00:05:13.289: INFO/GNU.IO(1335): RXTX fhs_lock() Error: creating lock file: /data/local/tmp/LCK..ttyS2: Permission denied
01-01 00:05:13.289: INFO/GNU.IO(1335): leaving RXTXPort:testRead no lock 
01-01 00:05:13.289: INFO/GNU.IO(1335): TestREAD.
01-01 00:05:13.289: INFO/GNU.IO(1335): /dev/ttyS3
01-01 00:05:13.289: INFO/GNU.IO(1335): entering RXTXPort:testRead 
01-01 00:05:13.289: INFO/GNU.IO(1335): RXTX fhs_lock() Error: creating lock file: /data/local/tmp/LCK..ttyS3: Permission denied
01-01 00:05:13.289: INFO/GNU.IO(1335): leaving RXTXPort:testRead no lock

**Comment by gascani** [comment]
Now the error is different...

01-01 00:05:13.203: INFO/GNU.IO(1335): RXTX fhs_lock() Error: creating lock file: /data/local/tmp/LCK..ttyS0: Permission denied

Give write permission also to /data/local/tmp folder

**Comment by aferre** [comment]
Thanks that was it.

Did you have to do this also?

**Comment by gascani** [comment]
yes :)

**Comment by vladistan** [comment]
No problem.  Curious if you can find it useful and what your project is.

**Comment by gascani** [comment]
I'm porting a java project for a USB device in Android. I use your project to read and write with the device.
